# Generated by Django 3.2.5 on 2021-07-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=100)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('isbn_number', models.CharField(blank=True, max_length=100, null=True)),
                ('pages_number', models.IntegerField(blank=True, null=True)),
                ('cover_link', models.CharField(blank=True, max_length=200, null=True)),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
